version: '3'

networks:
  web_net:
    ipam:
      config:
        - subnet: 192.168.96.0/24

services:
  web:
    image: httpd:latest
    restart: always
    ports:
    - "80:80"
    volumes:
    - ./htdocs:/usr/local/apache2/htdocs/
    networks:
      web_net:
        ipv4_address: 192.168.96.10
    environment:
      TZ: America/Bogota
